---
- name: Configure VLANs on Cisco Switch
  hosts: switches
  gather_facts: no
  tasks:

    - name: Create VLANs
      cisco.ios.ios_vlan:
        vlan_id: "{{ item.id }}"
        name: "{{ item.name }}"
        state: present
      loop:
        - { id: 10, name: "HR" }
        - { id: 20, name: "Tech" }
        - { id: 30, name: "Finance" }

    - name: Assign access ports to VLANs
      cisco.ios.ios_interfaces:
        config:
          - name: Ethernet0
            mode: access
            access_vlan: 10
          - name: Ethernet1
            mode: access
            access_vlan: 20
          - name: Ethernet2
            mode: access
            access_vlan: 30
      when: ansible_network_os == 'cisco.ios.ios'
