---
- name: Configure VLANs and access ports on Cisco switch for connected routers
  hosts: switches
  gather_facts: no
  tasks:

    - name: Create VLANs for each router
      cisco.ios.ios_vlan:
        vlan_id: "{{ item.id }}"
        name: "{{ item.name }}"
        state: present
      loop:
        - { id: 10, name: "VLAN_HR" }
        - { id: 20, name: "VLAN_TECH" }
        - { id: 30, name: "VLAN_FIN" }

    - name: Assign Cisco router port to VLAN 10 (HR)
      cisco.ios.ios_interfaces:
        config:
          - name: Ethernet0
            mode: access
            access_vlan: 10
            enabled: true

    - name: Assign Arista router port to VLAN 20 (TECH)
      cisco.ios.ios_interfaces:
        config:
          - name: Ethernet1
            mode: access
            access_vlan: 20
            enabled: true

    - name: Assign Juniper router port to VLAN 30 (FIN)
      cisco.ios.ios_interfaces:
        config:
          - name: Ethernet2
            mode: access
            access_vlan: 30
            enabled: true

